# Generated by Django 4.1.7 on 2023-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_natura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
