# Generated by Django 4.1.7 on 2023-03-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_natura', '0002_alter_products_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_unitPrice',
            field=models.FloatField(default=0, max_length=9),
        ),
    ]
