# Generated by Django 4.1.7 on 2023-03-05 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_natura', '0004_category_alter_products_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_unitPrice',
        ),
        migrations.AddField(
            model_name='products',
            name='product_line',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='products',
            name='product_url_line',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='api_natura.category'),
        ),
    ]
