# Generated by Django 4.1.7 on 2023-03-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_natura', '0006_alter_products_product_longdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_activeIngredient',
            field=models.CharField(default='', max_length=500),
        ),
    ]
