# Generated by Django 4.1.7 on 2023-03-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_natura', '0007_alter_products_product_activeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api_natura.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_longDescription',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
